// Tests for the pub cooldown gate (SECURITY.md §8). Pure logic only — the
// pub.dev fetch in tool/pub_cooldown.dart's main() is not exercised here.
import 'package:flutter_test/flutter_test.dart';

import '../tool/pub_cooldown.dart';

const _lockfile = '''
# Generated by pub
packages:
  analyzer:
    dependency: transitive
    description:
      name: analyzer
      sha256: deadbeef
      url: "https://pub.dev"
    source: hosted
    version: "12.1.0"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
  riverpod:
    dependency: transitive
    description:
      name: riverpod
      sha256: "cafe"
      url: "https://pub.dev"
    source: hosted
    version: "3.4.1"
sdks:
  dart: ">=3.10.0 <4.0.0"
''';

void main() {
  group('cooldownWindow', () {
    test('is 3 days (app policy — SECURITY.md §8)', () {
      expect(cooldownWindow, const Duration(days: 3));
    });
  });

  group('parseHostedPackages', () {
    test('returns hosted packages with their resolved versions', () {
      expect(parseHostedPackages(_lockfile), {
        'analyzer': '12.1.0',
        'riverpod': '3.4.1',
      });
    });

    test('skips sdk-sourced packages', () {
      expect(parseHostedPackages(_lockfile).containsKey('flutter'), isFalse);
    });

    test('ignores the sdks: section', () {
      expect(parseHostedPackages(_lockfile).containsKey('dart'), isFalse);
    });

    test('handles CRLF line endings', () {
      final crlf = _lockfile.replaceAll('\n', '\r\n');
      expect(parseHostedPackages(crlf), {
        'analyzer': '12.1.0',
        'riverpod': '3.4.1',
      });
    });

    test('handles a quoted source value', () {
      const lock = '''
packages:
  quoted_src:
    dependency: transitive
    source: "hosted"
    version: "1.0.0"
''';
      expect(parseHostedPackages(lock), {'quoted_src': '1.0.0'});
    });

    test('handles an unquoted version', () {
      const lock = '''
packages:
  plain:
    dependency: transitive
    source: hosted
    version: 1.2.3
''';
      expect(parseHostedPackages(lock), {'plain': '1.2.3'});
    });

    test('handles keys ordered with version before source', () {
      const lock = '''
packages:
  odd:
    dependency: transitive
    version: "9.9.9"
    source: hosted
''';
      expect(parseHostedPackages(lock), {'odd': '9.9.9'});
    });

    test('throws on malformed yaml rather than silently returning empty', () {
      expect(
        () => parseHostedPackages('packages:\n  - this is not a map\n'),
        throwsA(isA<FormatException>()),
      );
    });
  });

  group('resolveBaseRef', () {
    test('defaults to HEAD when unset', () {
      expect(resolveBaseRef(null), 'HEAD');
    });

    test('defaults to HEAD when empty or whitespace', () {
      // An empty COOLDOWN_BASE_REF is the dangerous case: `git show
      // ':./pubspec.lock'` succeeds and returns the *index* copy, which would
      // make the baseline identical to the working file and pass the gate.
      expect(resolveBaseRef(''), 'HEAD');
      expect(resolveBaseRef('   '), 'HEAD');
    });

    test('rejects the all-zero sha git uses for branch creation', () {
      expect(resolveBaseRef('0' * 40), isNull);
    });

    test('passes a real ref through, trimmed', () {
      expect(resolveBaseRef(' origin/main \n'), 'origin/main');
    });
  });

  group('unverifiedPackages', () {
    test('reports a changed package with no known publish date', () {
      expect(
        unverifiedPackages(
          resolved: {'riverpod': '3.4.2', 'ws': '3.0.3'},
          publishedAt: {'riverpod': DateTime.utc(2026, 7, 28)},
        ),
        ['ws'],
      );
    });

    test('is empty when every changed package has a date', () {
      expect(
        unverifiedPackages(
          resolved: {'riverpod': '3.4.2'},
          publishedAt: {'riverpod': DateTime.utc(2026, 7, 28)},
        ),
        isEmpty,
      );
    });

    test('does not report exempt packages', () {
      expect(
        unverifiedPackages(
          resolved: {'analyzer': '14.1.0'},
          publishedAt: const {},
          exempt: {'analyzer': 'SDK-pinned'},
        ),
        isEmpty,
      );
    });
  });

  group('changedVersions', () {
    test('returns packages whose version differs from the baseline', () {
      expect(
        changedVersions(
          current: {'riverpod': '3.4.2', 'ws': '3.0.3'},
          baseline: {'riverpod': '3.4.1', 'ws': '3.0.3'},
        ),
        {'riverpod': '3.4.2'},
      );
    });

    test('treats a newly added package as changed', () {
      expect(changedVersions(current: {'ulid': '2.0.1'}, baseline: const {}), {
        'ulid': '2.0.1',
      });
    });

    test('returns nothing when the lockfile is unchanged', () {
      expect(
        changedVersions(
          current: {'riverpod': '3.4.1'},
          baseline: {'riverpod': '3.4.1'},
        ),
        isEmpty,
      );
    });

    test('ignores packages dropped from the lockfile', () {
      expect(
        changedVersions(current: const {}, baseline: {'gone': '1.0.0'}),
        isEmpty,
      );
    });
  });

  group('findViolations', () {
    final now = DateTime.utc(2026, 7, 31);
    const cooldown = Duration(days: 7);

    test('flags a package published inside the cooldown window', () {
      final violations = findViolations(
        resolved: {'riverpod': '3.4.2'},
        publishedAt: {'riverpod': DateTime.utc(2026, 7, 28)},
        now: now,
        cooldown: cooldown,
      );
      expect(violations, hasLength(1));
      expect(violations.single.name, 'riverpod');
      expect(violations.single.version, '3.4.2');
      expect(violations.single.age, const Duration(days: 3));
    });

    test('accepts a package older than the cooldown', () {
      expect(
        findViolations(
          resolved: {'ws': '8.21.1'},
          publishedAt: {'ws': DateTime.utc(2026, 7, 14)},
          now: now,
          cooldown: cooldown,
        ),
        isEmpty,
      );
    });

    test('accepts a package exactly at the cooldown boundary', () {
      expect(
        findViolations(
          resolved: {'ws': '8.21.1'},
          publishedAt: {'ws': DateTime.utc(2026, 7, 24)},
          now: now,
          cooldown: cooldown,
        ),
        isEmpty,
      );
    });

    test('skips exempt packages', () {
      expect(
        findViolations(
          resolved: {'analyzer': '14.1.0'},
          publishedAt: {'analyzer': DateTime.utc(2026, 7, 30)},
          now: now,
          cooldown: cooldown,
          exempt: {'analyzer': 'SDK-pinned'},
        ),
        isEmpty,
      );
    });

    test('ignores packages with no known publish date', () {
      expect(
        findViolations(
          resolved: {'mystery': '1.0.0'},
          publishedAt: const {},
          now: now,
          cooldown: cooldown,
        ),
        isEmpty,
      );
    });

    test('sorts violations youngest first', () {
      final violations = findViolations(
        resolved: {'a': '1.0.0', 'b': '2.0.0'},
        publishedAt: {
          'a': DateTime.utc(2026, 7, 27),
          'b': DateTime.utc(2026, 7, 30),
        },
        now: now,
        cooldown: cooldown,
      );
      expect(violations.map((v) => v.name), ['b', 'a']);
    });
  });
}
